export const cleanItems = [
    // Node.js project clean options
    {
        value: 'node_modules/',
        template: ['default', 'node'],
        comment: 'Node.js dependencies (safe to delete and reinstall)',
    },
    {
        value: 'dist/',
        template: ['default', 'build'],
        comment: 'Build output folder',
    },
    {
        value: 'build/',
        template: ['default', 'build'],
        comment: 'Build directory',
    },
    {
        value: '.cache/',
        template: ['default', 'node', 'framework'],
        comment: 'Cache directory for various tools',
    },

    // Log files (often safe to clean)
    {
        value: 'npm-debug.log*',
        template: ['node', 'log'],
        comment: 'NPM debug logs',
    },
    {
        value: 'yarn-debug.log*',
        template: ['node', 'log'],
        comment: 'Yarn debug logs',
    },
    {
        value: 'yarn-error.log*',
        template: ['node', 'log'],
        comment: 'Yarn error logs',
    },
    {
        value: 'pnpm-debug.log*',
        template: ['node', 'log'],
        comment: 'PNPM debug logs',
    },

    // Testing and coverage folders
    {
        value: 'coverage/',
        template: ['test'],
        comment: 'Code coverage reports (safe to delete)',
    },
    {
        value: '.nyc_output/',
        template: ['test'],
        comment: 'NYC test coverage output',
    },

    // Temporary and backup files
    {
        value: '*.tmp',
        template: ['backup'],
        comment: 'Temporary files (generated by the system or tools)',
    },
    {
        value: '*.bak',
        template: ['backup'],
        comment: 'Backup files (check if you need these before deletion)',
    },
    {
        value: '~$*',
        template: ['backup'],
        comment: 'Temporary editor or system files',
    },

    // Framework and tool-specific caches and build outputs
    {
        value: '.next/',
        template: ['framework'],
        comment: 'Next.js build output (safe to delete)',
    },
    {
        value: '.nuxt/',
        template: ['framework'],
        comment: 'Nuxt.js build output (safe to delete)',
    },
    {
        value: '.parcel-cache/',
        template: ['framework'],
        comment: 'Parcel cache (safe to delete)',
    },
    {
        value: '.webpack/',
        template: ['framework'],
        comment: 'Webpack build output (safe to delete)',
    },
    {
        value: '.serverless/',
        template: ['framework'],
        comment: 'Serverless framework build output',
    },

    // Language-specific files (Python, Rust)
    {
        value: '__pycache__/',
        template: ['framework', 'python'],
        comment: 'Python bytecode cache',
    },
    {
        value: '*.py[cod]',
        template: ['framework', 'python'],
        comment: 'Python compiled files (safe to delete if untracked)',
    },
    {
        value: 'target/',
        template: ['framework', 'rust'],
        comment: 'Rust build output',
    },
];
