name: Publish to npm

on:
    push:
        branches:
            - main
        tags:
            - 'v*' # Esto permite publicar cuando se hace un tag de versión, como v1.0.0

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  registry-url: 'https://registry.npmjs.org/'

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            - name: Build the package
              run: npm run build

            - name: Publish to npm
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  if [ "$(git log -1 --pretty=%B)" == "release" ]; then
                    npm publish
                  fi
